name: Deploy to workers-site

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Install Wrangler
      run: sudo npm i @cloudflare/wrangler -g

    - name: Publish
      uses: cloudflare/wrangler-action@1.2.0
      env:
        USER: root
      with:
        apiToken: ${{ secrets.CF_API_TOKEN }}
        environment: 'production'
